using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace KTI.Moo.CRM.Model
{
    public class ProductsBase
    {
        public decimal currentcost { get; set; }
        public String defaultuomid { get; set; }
        public String defaultuomscheduleid { get; set; }
        public String description { get; set; }
        public int dmtimportstate { get; set; }
        public String entityimage { get; set; }
        public int importsequencenumber { get; set; }
        public bool iskit { get; set; }
        public bool isreparented { get; set; }
        public bool isstockitem { get; set; }
        public bool converttocustomerasset { get; set; }
        public String defaultvendor { get; set; }
        public int fieldserviceproducttype { get; set; }
        public String purchasename { get; set; }
        public bool taxable { get; set; }
        public String transactioncategory { get; set; }
        public String upccode { get; set; }
        [Required]
        public String name { get; set; }
        public DateTime overriddencreatedon { get; set; }
        public String parentproductid { get; set; }
        public decimal price { get; set; }
        public String pricelevelid { get; set; }
        public String processid { get; set; }
        public String productid { get; set; }
        [Required]
        public String productnumber { get; set; }
        public int productstructure { get; set; }
        public int productyypecode { get; set; }
        public String producturl { get; set; }
        public int quantitydecimal { get; set; }
        public decimal quantityonhand { get; set; }
        public String size { get; set; }
        public String stageid { get; set; }
        public decimal standardcost { get; set; }
        public int statecode { get; set; }
        public int statuscode { get; set; }
        public decimal stockvolume { get; set; }
        public decimal stockweight { get; set; }
        public String subjectid { get; set; }
        public String suppliername { get; set; }
        public String transactioncurrencyid { get; set; }
        public DateTime validfromdate { get; set; }
        public DateTime validtodate { get; set; }
        public String vendorid { get; set; }
        public String vendorname { get; set; }
        public String vendorpartnumber { get; set; }
        [Required]
        public String sku { get; set; }
        public string prodtype { get; set; }
        public string parentitem { get; set; }
        public string possku { get; set; }
        public string rp { get; set; }
        public string positemname { get; set; }
        public string category { get; set; }
        public string intensity { get; set; }
        public string ingallergn { get; set; }
        public string recycling { get; set; }
        public string recommend1 { get; set; }
        public string recommend2 { get; set; }
        public string recommend3 { get; set; }
        public string recommend4 { get; set; }
        public string matchgroup { get; set; }
        public string shortdesc { get; set; }
        public string specification { get; set; }
        public string acccategory { get; set; }
        public string collection { get; set; }
        public string color { get; set; }
        public string property { get; set; }
        //[Required]
        //public ProductPriceLevel pricelistitem { get; set; }

        public string AlternativeItemNumber { get; set; }
        public string AlternativeProductColorId { get; set; }
        public string AlternativeProductConfigurationId { get; set; }
        public string AlternativeProductSizeId { get; set; }
        public string AlternativeProductStyleId { get; set; }
        public string AlternativeProductUsageCondition { get; set; }
        public string AlternativeProductVersionId { get; set; }
        public string ApprovedVendorCheckMethod { get; set; }
        public double ApproximateSalesTaxPercentage { get; set; }
        public string AreTransportationManagementProcessesEnabled { get; set; }
        public int ArrivalHandlingTime { get; set; }
        public string BarcodeSetupId { get; set; }
        public string BatchMergeDateCalculationMethod { get; set; }
        public string BatchNumberGroupCode { get; set; }
        public int BestBeforePeriodDays { get; set; }
        public string BOMUnitSymbol { get; set; }
        public string BuyerGroupId { get; set; }
        public string CarryingCostABCCode { get; set; }
        public string CatchWeightItemHandlingPolicyName { get; set; }
        public string CatchWeightUnitSymbol { get; set; }
        public string CNPJ { get; set; }
        public string CommissionProductGroupId { get; set; }
        public string CommodityCodeId { get; set; }
        public string ComparisonPriceBaseUnitSymbol { get; set; }
        public double ConstantScrapQuantity { get; set; }
        public int ContinuityEventDuration { get; set; }
        public string ContinuityScheduleId { get; set; }
        public int CostCalculationBOMLevel { get; set; }
        public string CostCalculationGroupId { get; set; }
        public double CostChargesQuantity { get; set; }
        public string CostGroupId { get; set; }
        public string CustomsDescription { get; set; }
        public string CustomsExportTariffCode { get; set; }
        public string CustomsImportTariffCode { get; set; }
        public string DefaultDirectDeliveryWarehouse { get; set; }
        public int DefaultLedgerDimension { get; set; }
        public string DefaultLedgerDimensionDisplayValue { get; set; }
        public string DefaultOrderType { get; set; }
        public string DefaultProductConfigurationId { get; set; }
        public string DefaultProductStyleId { get; set; }
        public string DefaultProductVersionId { get; set; }
        public double DefaultReceivingQuantity { get; set; }
        public string DualUseCode { get; set; }
        public string Exempt { get; set; }
        public string FifthProductFilterCode { get; set; }
        public string FirstProductFilterCode { get; set; }
        public string FirstProductFilterGroupId { get; set; }
        public double FixedCostCharges { get; set; }
        public double FixedPurchasePriceCharges { get; set; }
        public double FixedSalesPriceCharges { get; set; }
        public string FlushingPrinciple { get; set; }
        public string FourthProductFilterCode { get; set; }
        public string FreightAllocationGroupId { get; set; }
        public double GrossDepth { get; set; }
        public double GrossProductHeight { get; set; }
        public double GrossProductWidth { get; set; }
        public string HSNCode { get; set; }
        public double IntrastatChargePercentage { get; set; }
        public string IntrastatCommodityCode { get; set; }
        public int InventCountingReasonCodePolicyRecId { get; set; }
        public string InventoryCountingReasonCodePolicyName { get; set; }
        public string InventoryGSTReliefCategoryCode { get; set; }
        public string InventoryReservationHierarchyName { get; set; }
        public string IsCatchWeightProduct { get; set; }
        public string IsDeliveredDirectly { get; set; }
        public string IsDiscountPosRegistrationProhibited { get; set; }
        public string IsDualUseProduct { get; set; }
        public string IsExemptFromAutomaticNotificationAndCancellation { get; set; }
        public string IsHazardousMaterial { get; set; }
        public string IsICMSTaxAppliedOnService { get; set; }
        public string IsInstallmentEligible { get; set; }
        public string IsIntercompanyPurchaseUsageBlocked { get; set; }
        public string IsIntercompanySalesUsageBlocked { get; set; }
        public string IsManualDiscountPosRegistrationProhibited { get; set; }
        public string IsPhantom { get; set; }
        public string IsPosRegistrationBlocked { get; set; }
        public string IsPosRegistrationQuantityNegative { get; set; }
        public string IsPurchasePriceAutomaticallyUpdated { get; set; }
        public string IsPurchasePriceIncludingCharges { get; set; }
        public string IsPurchaseWithholdingTaxCalculated { get; set; }
        public string IsRestrictedForCoupons { get; set; }
        public string IsRetailDiscountPosRegistrationProhibited { get; set; }
        public string IsSalesPriceAdjustmentAllowed { get; set; }
        public string IsSalesPriceIncludingCharges { get; set; }
        public string ISSALESWITHHOLDINGTAXCALCULATED { get; set; }
        public string IsScaleProduct { get; set; }
        public string IsShipAloneEnabled { get; set; }
        public string IsUnitCostAutomaticallyUpdated { get; set; }
        public string IsUnitCostIncludingCharges { get; set; }
        public string IsUnitCostProductVariantSpecific { get; set; }
        public string isVariantShelfLabelPrintingEnabled { get; set; }
        public string IsZeroPricePosRegistrationAllowed { get; set; }
        public string ItemFiscalClassificationCode { get; set; }
        public string ItemFiscalClassificationExceptionCode { get; set; }
        public string ItemModelGroupId { get; set; }
        public string ItemOverUnderDeliveryToleranceGroupId { get; set; }
        public string KeyInPriceRequirementsAtPOSRegister { get; set; }
        public string KeyInQuantityRequirementsAtPOSRegister { get; set; }
        public string LandedCostTypeGroupId { get; set; }
        public double LowerWarrantablePriceRangeLimit { get; set; }
        public string MarginAbcCode { get; set; }
        public double MaximumCatchWeightQuantity { get; set; }
        public double MaximumPickQuantity { get; set; }
        public double MinimumCatchWeightQuantity { get; set; }
        public string MustKeyInCommentAtPosRegister { get; set; }
        public string NecessaryProductionWorkingTimeSchedulingPropertyId { get; set; }
        public double NetProductWeight { get; set; }
        public int NGPCode { get; set; }
        public string NinthProductFilterCode { get; set; }
        public string NonGST { get; set; }
        public string OriginCountryRegionID { get; set; }
        public string OriginStateID { get; set; }
        public string PackageClassID { get; set; }
        public double PackingDutyQuantity { get; set; }
        public string PackingMaterialGroupID { get; set; }
        public string PackSizeCategoryID { get; set; }
        public string PhysicalDimensionGroupID { get; set; }
        public string PKWIUCode { get; set; }
        public string PlanningFormulaItemNumber { get; set; }
        public string PosRegistrationActivationDate { get; set; }
        public string PosRegistrationBlockedDate { get; set; }
        public string PosRegistrationPlannedBlockedDate { get; set; }
        public double PotencyBaseAttributeTargetValue { get; set; }
        public int PotencyBaseAttributeValueEntryEvent { get; set; }
        public string PrimaryVendorAccountNumber { get; set; }
        public string ProductCoverageGroupId { get; set; }
        public string ProductDimensionGroupName { get; set; }
        public string ProductFiscalInformationType { get; set; }
        public string ProductGroupId { get; set; }
        public double ProductionConsumptionDensityConversionFactor { get; set; }
        public double ProductionConsumptionDepthConversionFactor { get; set; }
        public double ProductionConsumptionHeightConversionFactor { get; set; }
        public double ProductionConsumptionWidthConversionFactor { get; set; }
        public string ProductionGroupId { get; set; }
        public string ProductionPoolId { get; set; }
        public string ProductionType { get; set; }
        public string ProductLifecycleSeasonCode { get; set; }
        public string ProductLifecycleStateId { get; set; }
        public string ProductSubtype { get; set; }
        public string ProductTaxationOrigin { get; set; }
        public double ProductVolume { get; set; }
        public string ProjectCategoryId { get; set; }
        public string PurchaseChargeProductGroupId { get; set; }
        public double PurchaseChargesQuantity { get; set; }
        public string PurchaseGstReliefCategoryCode { get; set; }
        public string PurchaseItemWithholdingTaxGroupCode { get; set; }
        public int PurchaseItemWithholdingTaxGroupCodeRecId { get; set; }
        public string PurchaseLineDiscountProductGroupCode { get; set; }
        public string PurchaseMultilineDiscountProductGroupCode { get; set; }
        public double PurchaseOverDeliveryPercentage { get; set; }
        public double PurchasePrice { get; set; }
        public DateTime PurchasePriceDate { get; set; }
        public double PurchasePriceQuantity { get; set; }
        public string PurchasePriceToleranceGroupId { get; set; }
        public int PurchasePricingPrecision { get; set; }
        public string PurchaseRebateProductGroupId { get; set; }
        public string PurchaseSalesTaxItemGroupCode { get; set; }
        public string PurchaseSupplementaryProductProductGroupId { get; set; }
        public double PurchaseUnderDeliveryPercentage { get; set; }
        public string PurchaseUnitSymbol { get; set; }
        public string RawMaterialPickingPrinciple { get; set; }
        public int ReservationHierarchyRecId { get; set; }
        public string RevenueAbcCode { get; set; }
        public string RevRecBundle { get; set; }
        public string RevRecDefaultRevenueRecognitionSchedule { get; set; }
        public string RevRecExcludeFromCarveOut { get; set; }
        public string RevRecMedianPrice { get; set; }
        public double RevRecMedianPriceMaximumTolerance { get; set; }
        public double RevRecMedianPriceMinimumTolerance { get; set; }
        public string RevRecRevenueRecognitionEnabled { get; set; }
        public string RevRecRevenueType { get; set; }
        public string SADGroup { get; set; }
        public DateTime SalePriceDate { get; set; }
        public double SalePriceQuantity { get; set; }
        public int SalePricingPrecision { get; set; }
        public string SalesChargeProductGroupId { get; set; }
        public double SalesChargesQuantity { get; set; }
        public string SalesGstReliefCategoryCode { get; set; }
        public string SalesItemWithholdingTaxGroupCode { get; set; }
        public int SalesItemWithholdingTaxGroupCodeRecId { get; set; }
        public string SalesLineDiscountProductGroupCode { get; set; }
        public string SalesMultilineDiscountProductGroupCode { get; set; }
        public double SalesOverdeliveryPercentage { get; set; }
        public double SalesPriceCalculationChargesPercentage { get; set; }
        public double SalesPriceCalculationContributionRatio { get; set; }
        public string SalesPriceCalculationModel { get; set; }
        public string SalesRebateProductGroupId { get; set; }
        public double SalesRetailInventoryAvailabilityBuffer { get; set; }
        public string SalesRetailInventoryAvailabilityLevelProfile { get; set; }
        public string SalesSalesTaxItemGroupCode { get; set; }
        public string SalesSupplementaryProductProductGroupId { get; set; }
        public string SalesUnitSymbol { get; set; }
        public string SATCode { get; set; }
        public string ScaleIndicator { get; set; }
        public string SecondProductFilterCode { get; set; }
        public string SecondProductFilterGroupId { get; set; }
        public string SellEndDate { get; set; }
        public string SellStartDate { get; set; }
        public string SerialNumberGroupCode { get; set; }
        public string ServiceAccountingCode { get; set; }
        public string ServiceFiscalInformationCode { get; set; }
        public string ServiceType { get; set; }
        public string SeventhProductFilterCode { get; set; }
        public int ShelfAdvicePeriodDays { get; set; }
        public int ShelfLifePeriodDays { get; set; }
        public int ShippingAndReceivingSortOrderCode { get; set; }
        public string ShipStartDate { get; set; }
        public string SixthProductFilterCode { get; set; }
        public string StorageDimensionGroupName { get; set; }
        public int StorageDimensionGroupRecId { get; set; }
        public double TareProductWeight { get; set; }
        public int TaxGstReliefCategoryInvent { get; set; }
        public double TaxSubstitutionCode { get; set; }
        public string TenthProductFilterCode { get; set; }
        public string ThirdProductFilterCode { get; set; }
        public string TrackingDimensionGroupName { get; set; }
        public int TrackingDimensionGroupRecId { get; set; }
        public string TransferOrderLandedCostGroupId { get; set; }
        public double TransferOrderOverDeliveryPercentage { get; set; }
        public double TransferOrderUnderDeliveryPercentage { get; set; }
        public string UnitConversionSequenceGroupId { get; set; }
        public string UnitCostDate { get; set; }
        public double UnitCostQuantity { get; set; }
        public string UpdateProductVariantLifecycleState { get; set; }
        public double UpperWarrantablePriceRangeLimit { get; set; }
        public string UsTenderDiscountPOSRegistrationProhibited { get; set; }
        public string ValueAbcCode { get; set; }
        public double VariableScrapPercentage { get; set; }
        public string VendorInvoiceLineMatchingPolicy { get; set; }
        public string VoyageArrivalGroupId { get; set; }
        public string WarehouseFilterCode { get; set; }
        public string WarehouseFilterGroup { get; set; }
        public string WarehouseMobileDeviceDescriptionLine1 { get; set; }
        public string WarehouseMobileDeviceDescriptionLine2 { get; set; }
        public string WarehouseReleaseSalesUnitRestricted { get; set; }
        public string WarrantablePriceRangeBaseType { get; set; }
        public int WarrantyDurationTime { get; set; }
        public int WarrantyDurationTimeUnit { get; set; }
        public string WillInventIssueAutoReportAsFinished { get; set; }
        public string WillInventReceiptIgnoreFlushingPrinciple { get; set; }
        public string WillPickingWorkbenchApplyBoxingLogic { get; set; }
        public string WillTotalPurchaseDiscountCalculationIncludeProduct { get; set; }
        public string WillTotalSalesDiscountCalculationIncludeProduct { get; set; }
        public string WillWorkCenterPickingAllowNegativeInventory { get; set; }
        public double YieldPercentage { get; set; }
        [Required]
        [DataType(DataType.Text)]
        public string moosourcesystem { get; set; }
        //Customized
        [DataType(DataType.Text)]
        public string mooexternalid { get; set; }
        //Customized
        //[CompanyIdAttribute]
        public int companyid { get; set; }
    }
}
