using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace CRM_Plugin.CustomAPI.Helper.EntityHelper
{
    public class Customer
    {

        public static string sap_customer_card_code = "sap_customer_card_code";
        public static string accountrolecode = "accountrolecode";
        public static string address1_addressid = "address1_addressid";
        public static string address1_addresstypecode = "address1_addresstypecode";
        public static string address1_city = "address1_city";
        public static string address1_country = "address1_country";
        public static string address1_county = "address1_county";
        public static string address1_fax = "address1_fax";
        public static string address1_freighttermscode = "address1_freighttermscode";
        public static string address1_latitude = "address1_latitude";
        public static string address1_line1 = "address1_line1";
        public static string address1_line2 = "address1_line2";
        public static string address1_line3 = "address1_line3";
        public static string address1_longitude = "address1_longitude";
        public static string address1_name = "address1_name";
        public static string address1_postalcode = "address1_postalcode";
        public static string address1_postofficebox = "address1_postofficebox";
        public static string address1_primarycontactname = "address1_primarycontactname";
        public static string address1_shippingmethodcode = "address1_shippingmethodcode";
        public static string address1_stateorprovince = "address1_stateorprovince";
        public static string address1_telephone1 = "address1_telephone1";
        public static string address1_telephone2 = "address1_telephone2";
        public static string address1_telephone3 = "address1_telephone3";
        public static string address1_upszone = "address1_upszone";
        public static string address1_utcoffset = "address1_upszone";
        public static string address2_addressid = "address2_addressid";
        public static string address2_addresstypecode = "address2_addresstypecode";
        public static string address2_city = "address2_city";
        public static string address2_country = "address2_country";
        public static string address2_county = "address2_county";
        public static string address2_fax = "address2_fax";
        public static string address2_freighttermscode = "address2_freighttermscode";
        public static string address2_latitude = "address2_latitude";
        public static string address2_line1 = "address2_line1";
        public static string address2_line2 = "address2_line2";
        public static string address2_line3 = "address2_line3";
        public static string address2_longitude = "address2_longitude";
        public static string address2_name = "address2_name";
        public static string address2_postalcode = "address2_postalcode";
        public static string address2_postofficebox = "address2_postofficebox";
        public static string address2_primarycontactname = "address2_primarycontactname";
        public static string address2_shippingmethodcode = "address2_shippingmethodcode";
        public static string address2_stateorprovince = "address2_stateorprovince";
        public static string address2_telephone1 = "address2_telephone1";
        public static string address2_telephone2 = "address2_telephone2";
        public static string address2_telephone3 = "address2_telephone3";
        public static string address2_upszone = "address2_upszone";
        public static string address2_utcoffset = "address2_utcoffset";
        public static string address3_addressid = "address3_addressid";
        public static string address3_addresstypecode = "address3_addresstypecode";
        public static string address3_city = "address3_city";
        public static string address3_country = "address3_country";
        public static string address3_county = "address3_county";
        public static string address3_fax = "address3_fax";
        public static string address3_freighttermscode = "address3_freighttermscode";
        public static string address3_latitude = "address3_latitude";
        public static string address3_line1 = "address3_line1";
        public static string address3_line2 = "address3_line2";
        public static string address3_line3 = "address3_line3";
        public static string address3_longitude = "address3_longitude";
        public static string address3_name = "address3_name";
        public static string address3_postalcode = "address3_postalcode";
        public static string address3_postofficebox = "address3_postofficebox";
        public static string address3_primarycontactname = "address3_primarycontactname";
        public static string address3_shippingmethodcode = "address3_shippingmethodcode";
        public static string address3_stateorprovince = "address3_stateorprovince";
        public static string address3_telephone1 = "address3_telephone1";
        public static string address3_telephone2 = "address3_telephone2";
        public static string address3_telephone3 = "address3_telephone3";
        public static string address3_upszone = "address3_upszone";
        public static string address3_utcoffset = "address3_utcoffset";
        public static string anniversary = "anniversary";
        public static string annualincome = "annualincome";
        public static string assistantname = "assistantname";
        public static string assistantphone = "assistantphone";
        public static string birthdate = "birthdate";
        public static string business2 = "business2";
        public static string callback = "callback";
        public static string childrensnames = "childrensnames";
        public static string company = "company";
        public static string contactid = "contactid";
        public static string creditlimit = "creditlimit";
        public static string creditonhold = "creditonhold";
        public static string customersizecode = "customersizecode";
        public static string customertypecode = "customertypecode";
        public static string defaultpricelevelid = "defaultpricelevelid";
        public static string department = "department";
        public static string description = "description";
        public static string donotbulkemail = "donotbulkemail";
        public static string donotbulkpostalmail = "donotbulkpostalmail";
        public static string donotemail = "donotemail";
        public static string donotfax = "donotfax";
        public static string donotphone = "donotphone";
        public static string donotpostalmail = "donotpostalmail";
        public static string donotsendmm = "donotsendmm";
        public static string educationcode = "educationcode";
        public static string emailaddress1 = "emailaddress1";
        public static string emailaddress2 = "emailaddress2";
        public static string emailaddress3 = "emailaddress3";
        public static string employeeid = "employeeid";
        public static string entityimage = "entityimage";
        public static string externaluseridentifier = "externaluseridentifier";
        public static string familystatuscode = "familystatuscode";
        public static string fax = "fax";
        public static string firstname = "firstname";
        public static string followemail = "followemail";
        public static string ftpsiteurl = "ftpsiteurl";
        public static string gendercode = "gendercode";
        public static string governmentid = "governmentid";
        public static string haschildrencode = "haschildrencode";
        public static string home2 = "home2";
        public static string importsequencenumber = "importsequencenumber";
        public static string isbackofficecustomer = "isbackofficecustomer";
        public static string jobtitle = "jobtitle";
        public static string lastname = "lastname";
        public static string lastonholdtime = "lastonholdtime";
        public static string lastusedincampaign = "lastusedincampaign";
        public static string leadsourcecode = "leadsourcecode";
        public static string managername = "managername";
        public static string managerphone = "managerphone";
        public static string marketingonly = "marketingonly";
        public static string middlename = "middlename";
        public static string mobilephone = "mobilephone";
        public static string orgchangestatus = "orgchangestatus";
        public static string nickname = "nickname";
        public static string numberofchildren = "numberofchildren";
        public static string originatingleadid = "originatingleadid";
        public static string overriddencreatedon = "overriddencreatedon";
        public static string ownerid = "ownerid";
        public static string owneridtype = "owneridtype";
        public static string pager = "pager";
        public static string parentcustomerid = "parentcustomerid";
        public static string parentcustomeridtype = "parentcustomeridtype";
        public static string participatesinworkflow = "participatesinworkflow";
        public static string paymenttermscode = "paymenttermscode";
        public static string preferredappointmentdaycode = "preferredappointmentdaycode";
        public static string preferredappointmenttimecode = "preferredappointmenttimecode";
        public static string preferredcontactmethodcode = "preferredcontactmethodcode";
        public static string preferredequipmentid = "preferredequipmentid";
        public static string preferredserviceid = "preferredserviceid";
        public static string preferredsystemuserid = "preferredsystemuserid";
        public static string processid = "processid";
        public static string salutation = "salutation";
        public static string shippingmethodcode = "shippingmethodcode";
        public static string slaid = "slaid";
        public static string spousesname = "spousesname";
        public static string stageid = "stageid";
        public static string statecode = "statecode";
        public static string statuscode = "statuscode";
        public static string subscriptionid = "subscriptionid";
        public static string suffix = "suffix";
        public static string teamsfollowed = "teamsfollowed";
        public static string telephone1 = "telephone1";
        public static string telephone2 = "telephone2";
        public static string telephone3 = "telephone3";
        public static string territorycode = "territorycode";
        public static string transactioncurrencyid = "transactioncurrencyid";
        public static string websiteurl = "websiteurl";
        public static string yomifirstname = "yomifirstname";
        public static string yomilastname = "yomilastname";
        public static string yomimiddlename = "yomimiddlename";
        public static string sourcesystem = "sourcesystem";
        public static string clubmembershipid = "clubmembershipid";
        public static string country = "country";
        public static string customerjoineddate = "customerjoineddate";
        public static string customerjoinedoutlet = "customerjoinedoutlet";
        public static string firstpointofpurchase = "firstpointofpurchase";
        public static string customertype = "customertype";
        public static string customerseniority = "customerseniority";
        public static string lastcoffeepurchasedate = "lastcoffeepurchasedate";
        public static string customerstatus = "customerstatus";
        public static string changeofstatusdate = "changeofstatusdate";
        public static string customertier = "customertier";
        public static string totalcoffeeqtyytd = "totalcoffeeqtyytd";
        public static string totalmachineqtyytd = "totalmachineqtyytd";
        public static string grandtotalcoffeeqty = "grandtotalcoffeeqty";
        public static string grandtotalmachineqty = "grandtotalmachineqty";
        public static string channel = "channel";
        public static string soremarks = "soremarks";
        public static string membercode = "membercode";
        public static string acct_w_concern = "acct_w_concern";
        public static string kas_name = "kas_name";
        public static string checkname = "checkname";
        public static string contactperson = "contactperson";
        public static string moosourcesystem = "moosourcesystem";
        public static string MooExternalId = "MooExternalId";
        public static string kti_socialchannelorigin = "kti_socialchannelorigin";
        public static string kti_sourceid = "kti_sourceid";






        //Custom fields
        public static string companyid = "companyid";
        public static string ncci_customerjoinedbranch = "ncci_customerjoinedbranch";



        public static string kti_customerDTO = "kti_customerDTO";
        public static string response = "kti_ResponseValue";
        public static string response_message_created = "Customer successfully created";
        public static string response_message_updated = "Customer successfully updated";
    }
}
