using Microsoft.EntityFrameworkCore.Metadata.Internal;
using System.Reflection.Metadata;

namespace KTI.Moo.FO.Model;

    public class CustomerBase //: Base.Model.CustomerBase
    {
        public virtual string dataAreaId { get; set; }
        public virtual string PrimaryContactEmail { get; set; }
        public virtual string DeliveryAddressCounty { get; set; }
        public virtual string InvoiceAddressStreet { get; set; }
        public virtual string InvoiceAddressDistrictName { get; set; }
        public virtual string AddressZipCode { get; set; }
        public virtual string PrimaryContactFax { get; set; }
        public virtual string AddressCity { get; set; }
        public virtual string PrimaryContactURL { get; set; }
        public virtual string PrimaryContactEmailDescription { get; set; }
        public virtual string PrimaryContactPhone { get; set; }
        public virtual string DeliveryAddressCity { get; set; }
        public virtual string InvoiceAddressCounty { get; set; }
        public virtual string DeliveryAddressStreet { get; set; }
        public virtual string SalesCurrencyCode { get; set; }
        public virtual string PersonFirstName { get; set; }
        public virtual string AddressState { get; set; }
        public virtual string InvoiceAddressStreetNumber { get; set; }
        public virtual string InvoiceAddressState { get; set; }
        public virtual string DeliveryAddressState { get; set; }
        public virtual string PersonLastNamePrefix { get; set; }
        public virtual string PersonPhoneticMiddleName { get; set; }
        public virtual int AddressLatitude { get; set; }
        public virtual string DeliveryAddressDistrictName { get; set; }
        public virtual string DeliveryAddressStreetNumber { get; set; }
        public virtual int InvoiceAddressLongitude { get; set; }
        public virtual int InvoiceAddressLatitude { get; set; }
        public virtual string OrganizationName { get; set; }
        public virtual string PrimaryContactPhoneDescription { get; set; }
        public virtual string AddressPostbox { get; set; }
        public virtual string AddressCounty { get; set; }
        public virtual string NameAlias { get; set; }
        public virtual string AddressStreetNumber { get; set; }
        public virtual string PersonLastName { get; set; }
        public virtual string InvoiceAddressZipCode { get; set; }
        public virtual string IsOneTimeCustomer { get; set; }
        public virtual string CustomerGroupId { get; set; }
        public virtual string DeliveryAddressZipCode { get; set; }
        public virtual string AddressDescription { get; set; }
        public virtual string PersonPhoneticFirstName { get; set; }
        public virtual int DeliveryAddressLatitude { get; set; }
        public virtual string PersonMiddleName { get; set; }
        public virtual string LanguageId { get; set; }
        public virtual string PersonPhoneticLastName { get; set; }
        public virtual string AddressStreet { get; set; }

        #region oldfields
        //public virtual string AccountNum { get; set; }
        //public virtual string AccountStatement { get; set; }
        //public virtual bool Affiliated_RU { get; set; }
        //public virtual string AgencyLocationCode { get; set; }
        //public virtual string AuthorityOffice_IT { get; set; }
        //public virtual string BankAccount { get; set; }
        //public virtual string BankCentralBankPurposeCode { get; set; }
        //public virtual string BankCentralBankPurposeText { get; set; }
        //public virtual string BankCustPaymIdTable { get; set; }
        //public virtual string BirthCountyCode_IT { get; set; }
        //public virtual string BirthPlace_IT { get; set; }
        //public virtual string Blocked { get; set; }
        //public virtual bool BlockFloorLimitUseInChannel { get; set; }
        //public virtual string CashDisc { get; set; }
        //public virtual string CashDiscBaseDays { get; set; }
        //public virtual string CCMNum_BR { get; set; }
        //public virtual bool CFDIEnabled_MX { get; set; }
        //public virtual bool CFDISkipIEPSTaxes_MX { get; set; }
        //public virtual bool CFDITempraryExport_MX { get; set; }
        //public virtual string ClearingPeriod { get; set; }
        //public virtual string CNAE_BR { get; set; }
        //public virtual string CNPJCPFNum_BR { get; set; }
        //public virtual string CollectionLetterCode { get; set; }
        //public virtual string CommercialRegister { get; set; }
        //public virtual string CommercialRegisterInsetNumber { get; set; }
        //public virtual string CommissionGroup { get; set; }
        //public virtual string CompanyChainId { get; set; }
        //public virtual string CompanyIdSiret { get; set; }
        //public virtual string CompanyNAFCode { get; set; }
        //public virtual string CopmanyType_MX { get; set; }
        //public virtual int ConsDay_JP { get; set; }
        //public virtual string ContactPersonId { get; set; }
        //public virtual string CreditCardAddressVerification { get; set; }
        //public virtual string CreditCardAddressVerificationLevel { get; set; }
        //public virtual bool CreditCardAddressVerificationVoid { get; set; }
        //public virtual string CreditCardCVC { get; set; }
        //public virtual decimal CreditMax { get; set; }
        //public virtual string CreditRating { get; set; }
        //public virtual string CredManAccountStatusId { get; set; }
        //public virtual DateTime CredManBusinessStarted { get; set; }
        //public virtual string CredManCollectionGroupId { get; set; }
        //public virtual string CredManCreditLimitDate { get; set; }
        //public virtual DateTime CredManCreditLimitExpiryDate { get; set; }
        //public virtual decimal CredManCustCreditLimitMaxAlt { get; set; }
        //public virtual DateTime CredManCustomerSince { get; set; }
        //public virtual bool CredManCustUnlimitedCredit { get; set; }
        //public virtual string CredManEligibleCreditLimitCurrency { get; set; }
        //public virtual string CredManEligibleCreditLimitDate { get; set; }
        //public virtual decimal CredManEligibleCreditMax { get; set; }
        //public virtual bool CredManExclude { get; set; }
        //public virtual string CredManGroupId { get; set; }
        //public virtual DateTime CredManLastReviewDate { get; set; }
        //public virtual DateTime CredManNextSchedReviewDate { get; set; }
        //public virtual string CredManNotes { get; set; }
        //public virtual string CredManStatusReasonId { get; set; }
        //public virtual bool CredManTitleHeld { get; set; }
        //public virtual bool CredManWithAgency { get; set; }
        //public virtual string Curp_MX { get; set; }
        //public virtual string Currency { get; set; }
        //public virtual string CustClassificationId { get; set; }
        //public virtual bool CustExcludeCollectionFee { get; set; }
        //public virtual bool CustExcludeInterestCharges { get; set; }
        //public virtual bool CustFinalUser_BR { get; set; }
        //public virtual string CustGroup { get; set; }
        //public virtual string CustItemGroupId { get; set; }
        //public virtual string CustTradingPartnerCode { get; set; }
        //public virtual string CustWhtContributionType_BR { get; set; }
        //public virtual bool CustWriteOffRefRecId { get; set; }
        //public virtual string DefaultDirectDebitMandate { get; set; }
        //public virtual string DefaultInventStatusId { get; set; }
        //public virtual string DestinationCodeId { get; set; }
        //public virtual string DlvMode { get; set; }
        //public virtual string DlvReason { get; set; }
        //public virtual string DlvTerm { get; set; }
        //public virtual bool EInvoice { get; set; }
        //public virtual bool EInvoiceAttachment { get; set; }
        //public virtual string EInvoiceEANNum { get; set; }
        //public virtual bool EInvoiceRegister_IT { get; set; }
        //public virtual string EndDisc { get; set; }
        //public virtual bool EntryCertificateRequired_W { get; set; }
        //public virtual bool ExportSales_PL { get; set; }
        //public virtual bool ExpressBillOfLading { get; set; }
        //public virtual string FactoringAccount { get; set; }
        //public virtual string FederalComments { get; set; }
        //public virtual string FedNonFedIndicator { get; set; }
        //public virtual string FineCode_BR { get; set; }
        //public virtual string FiscalCode { get; set; }
        //public virtual string FiscalCode_PL { get; set; }
        //public virtual bool ForecastDMPInclude { get; set; }
        //public virtual string ForeignerId_BR { get; set; }
        //public virtual bool ForeignResident_RU { get; set; }
        //public virtual string ForeignTaxRegistration_MX { get; set; }
        //public virtual bool ForeignTrade_MX { get; set; }
        //public virtual string FreeNotesGroup_IT { get; set; }
        //public virtual string FreightZone { get; set; }
        //public virtual bool GenerateIncomingFiscalDocument_BR { get; set; }
        //public virtual string GiroType { get; set; }
        //public virtual string GiroTypeAccountStatement { get; set; }
        //public virtual string GiroTypeCollectionletter { get; set; }
        //public virtual string GiroTypeInterestNote { get; set; }
        //public virtual string GiroTypeProjInvoice { get; set; }
        //public virtual bool ICMSContributor_BR { get; set; }

        //public virtual string IENum_BR { get; set; }
        //public virtual bool InclTax { get; set; }
        //public virtual string INSSCEI_BR { get; set; }
        //public virtual string IntBank_LV { get; set; }
        //public virtual bool InterCompanyAllowIndirectCreation { get; set; }
        //public virtual bool InterCompanyAutoCreateOrders { get; set; }
        //public virtual bool InterCompanyDirectDelivery { get; set; }
        //public virtual string InterestCode_BR { get; set; }
        //public virtual string InventLocation { get; set; }
        //public virtual string InventProfileId_RU { get; set; }
        //public virtual string InventProfileType_RU { get; set; }
        //public virtual string InventSiteId { get; set; }
        //public virtual string InvoiceAccount { get; set; }
        //public virtual string InvoiceAddress { get; set; }
        //public virtual string InvoicePostingType_RU { get; set; }
        //public virtual bool IRS1099CIndicator { get; set; }
        //public virtual bool IsExternallyMaintained { get; set; }
        //public virtual bool IsResident_LV { get; set; }
        //public virtual bool IssueOwnEntryCertificate_W { get; set; }
        //public virtual string IsserCountry_HU { get; set; }
        //public virtual string LineDisc { get; set; }
        //public virtual string LineOfBusinessId { get; set; }
        //public virtual string LvPaymTransCode { get; set; }
        //public virtual string MainContactWorker { get; set; }
        //public virtual bool MandatoryCreditLimit { get; set; }
        //public virtual bool MandatoryvatDate_PL { get; set; }
        //public virtual string MarkupGroup { get; set; }
        //public virtual string MCRMergedParent { get; set; }
        //public virtual string MCRMergedRoot { get; set; }
        //public virtual string Memo { get; set; }
        //public virtual string MultiLineDisc { get; set; }
        //public virtual string NIT_BR { get; set; }
        //public virtual string numberSequenceGroup { get; set; }
        //public virtual bool OneTimeCustomer { get; set; }
        //public virtual string OrderEntryDeadlineGroupId { get; set; }
        //public virtual string OrgId { get; set; }
        //public virtual string OurAccountNum { get; set; }
        //public virtual bool OverrideSalesTax { get; set; }
        //public virtual bool PackageDepositExcempt_PL { get; set; }
        //public virtual string PackMaterialFeeLicenseNum { get; set; }
        //public virtual string Party { get; set; }
        //public virtual string PartyCountry { get; set; }
        //public virtual string PartyState { get; set; }
        //public virtual string PassportNo_HU { get; set; }
        //public virtual string PaymDayId { get; set; }
        //public virtual string PaymentReference_EE { get; set; }
        //public virtual string PaymMode { get; set; }
        //public virtual string PaymSched { get; set; }
        //public virtual string PaymSpec { get; set; }
        //public virtual string PaymTermId { get; set; }
        //public virtual string PdsCustRebateGroupId { get; set; }
        //public virtual bool PdsFreightAccrued { get; set; }
        //public virtual string PdsRebateTMAGroup { get; set; }
        //public virtual string PHT_TINNumber { get; set; }
        //public virtual string PHT_TradeName { get; set; }
        //public virtual string PresenceType_BR { get; set; }
        //public virtual string PriceGroup { get; set; }
        //public virtual string ResidenceForeignCountryRegionId_IT { get; set; }
        //public virtual bool RevRecDisableIntercompany { get; set; }
        //public virtual string Rfc_MX { get; set; }
        //public virtual string SalesCalendarId { get; set; }
        //public virtual string SalesDistrictId { get; set; }
        //public virtual string SalesGroup { get; set; }
        //public virtual string SalesPoolId { get; set; }
        //public virtual string SATPaymMethod_MX { get; set; }
        //public virtual string SATPurpose_MX { get; set; }
        //public virtual string SegmentId { get; set; }
        //public virtual bool ServiceCodeOnDlvAddress_BR { get; set; }
        //public virtual bool SimpleNational_BR { get; set; }
        //public virtual bool SimplifyTaxIntgrExportDocValidation_CN { get; set; }
        //public virtual string StateInsciption_MX { get; set; }
        //public virtual string StatisticsGroup { get; set; }
        //public virtual string SubsegmentId { get; set; }
        //public virtual string SuframaNumber_BR { get; set; }
        //public virtual bool SuframaPISCOFINS_BR { get; set; }
        //public virtual bool Suframa_BR { get; set; }
        //public virtual string SuppItemGroupId { get; set; }
        //public virtual string TaxGroup { get; set; }
        //public virtual string TaxGTSReliefGroupHeading_MY { get; set; }
        //public virtual string TaxLicenseNum { get; set; }
        //public virtual string TaxPeriodPaymentCode_PL { get; set; }
        //public virtual string TaxRegimeCode_MX { get; set; }
        //public virtual bool TaxWithholdCalculate_IN { get; set; }
        //public virtual bool TaxWithholdCalculate_TH { get; set; }
        //public virtual string TaxWithholdGroup_TH { get; set; }
        //public virtual bool UnitedVATInvoice_LT { get; set; }
        //public virtual string UseCashDisc { get; set; }
        //public virtual bool UseOriginalDocumentAsFacture_RU { get; set; }
        //public virtual bool usePurchRequest { get; set; }
        //public virtual string VATNum { get; set; }
        //public virtual string VendAccount { get; set; }
        //public virtual string WebSalesOrderDisplay { get; set; }
        //public virtual string WorkflowState { get; set; }
        //public virtual DateTime modifiedDateTime { get; set; }
        //public virtual string modifiedBy { get; set; }
        //public virtual DateTime createdDateTime { get; set; }
        //public virtual string dataAreaId { get; set; }
        //public virtual int recversion { get; set; }
        //public virtual int Partition { get; set; }
        //public virtual int RecId { get; set; }
        #endregion
}


