using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace Moo.FO.Model
{
    public class StoreTransactionLines
    {
        public string dataAreaId { get; set; }
        public string Terminal { get; set; }
        public string TransactionNumber { get; set; }
        public int LineNumber { get; set; }
        public string OperatingUnitNumber { get; set; }
        public decimal CustomerDiscount { get; set; }
        public string RequestedReceiptDate { get; set; }
        public decimal CashDiscountAmount { get; set; }
        public string TransactionDate { get; set; }
        public string OriginalItemSalesTaxGroup { get; set; }
        public string SiteId { get; set; }
        public string RetailEmailAddressContent { get; set; }
        public string ItemSize { get; set; }
        public string ModeOfDelivery { get; set; }
        public string SkipReports { get; set; }
        public string Warehouse { get; set; }
        public int PickupStartTime { get; set; }
        public decimal TotalDiscount { get; set; }
        public decimal TaxExemptPriceInclusiveOriginalPrice { get; set; }
        public string IsLinkedProductNotOriginal { get; set; }
        public decimal DiscountAmountWithoutTax { get; set; }
        public decimal NetPrice { get; set; }
        public string PriceGroups { get; set; }
        public string RFIDTagId { get; set; }
        public string VariantNumber { get; set; }
        public string CategoryHierarchyName { get; set; }
        public string TransactionCode { get; set; }
        public decimal TotalDiscountPercentage { get; set; }
        public decimal FixedPriceCharges { get; set; }
        public string Unit { get; set; }
        public decimal TaxExemptPriceInclusiveReductionAmount { get; set; }
        public string PriceInBarCode { get; set; }
        public string LotID { get; set; }
        public decimal ReturnQuantity { get; set; }
        public string CustomerAccount { get; set; }
        public decimal OriginalPrice { get; set; }
        public string ItemRelation { get; set; }
        public string RequestedShipDate { get; set; }
        public string TransactionStatus { get; set; }
        public string ItemConfigId { get; set; }
        public string Currency { get; set; }
        public string ReturnOperatingUnitNumber { get; set; }
        public decimal LineDiscount { get; set; }
        public decimal NetAmountInclusiveTax { get; set; }
        public string InventoryStatus { get; set; }
        public decimal LineManualDiscountPercentage { get; set; }
        public string GiftCard { get; set; }
        public string ChannelListingID { get; set; }
        public decimal NetAmount { get; set; }
        public string ItemColor { get; set; }
        public string IsPriceChange { get; set; }
        public string BarCode { get; set; }
        //public Decimal UnitQuantity { get; set; }
        public decimal LineManualDiscountAmount { get; set; }
        public decimal StandardNetPrice { get; set; }
        public string ItemVersion { get; set; }
        public string ReturnTerminal { get; set; }
        public string IsWeightProduct { get; set; }
        public string LogisticLocationId { get; set; }
        public string IsScaleProduct { get; set; }
        public string IsOriginalOfLinkedProductList { get; set; }
        public string ItemStyle { get; set; }
        public string ReceiptNumber { get; set; }
        public decimal LinePercentageDiscount { get; set; }
        public int ReasonCodeDiscount { get; set; }
        public string CategoryName { get; set; }
        public int TotalDiscountInfoCodeLineNum { get; set; }
        public string KeyboardProductEntry { get; set; }
        public string CancelledTransactionNumber { get; set; }
        public string IsReturnNoSale { get; set; }
        public string ElectronicDeliveryEmail { get; set; }
        public string ItemId { get; set; }
        public decimal SalesTaxAmount { get; set; }
        public string ReturnTransactionNumber { get; set; }
        public Decimal Quantity { get; set; }
        public decimal Price { get; set; }
        public decimal UnitPrice { get; set; }
        public string SalesTaxGroup { get; set; }
        public string OriginalSalesTaxGroup { get; set; }
        public string ShelfNumber { get; set; }
        public string ItemSalesTaxGroup { get; set; }
        public string SerialNumber { get; set; }
        public string OfferNumber { get; set; }
        public string SectionNumber { get; set; }
        public string IsWeightManuallyEntered { get; set; }
        public decimal DiscountAmountForPrinting { get; set; }
        public decimal CustomerInvoiceDiscountAmount { get; set; }
        public string ProductScanned { get; set; }
        public decimal PeriodicDiscountPercentage { get; set; }
        public string ReturnTrackingStatus { get; set; }
        public int ReturnLineNumber { get; set; }
        public decimal PeriodicDiscountAmount { get; set; }
        public string PeriodicDiscountGroup { get; set; }
        public string LogisticsPostalAddressValidFrom { get; set; }
        public int PickupEndTime { get; set; }
        public string BusinessDate { get; set; }
        public string store { get; set; }
        //public int Channel { get; set; }
        //public string IsLineDiscounted { get; set; }
        //public decimal CostAmount { get; set; }
        //public int LogisticPostalAddressID { get; set; }
        //public int CatalogID { get; set; }
        //public int CategoryID { get; set; }
        //public int ModifiedTransactionID { get; set; }
        //public int CreatedTransactionID { get; set; }
        //public DateTimeOffset ModifiedDateTime { get; set; }
        //public string ModifiedBy { get;}
        //public DateTimeOffset CreatedDateTime { get; set; }
        //public string CreatedBy { get; }
        //public int RecVersion { get; set; }
        //public int Partition { get; set; }
        //public int RecID { get; set; }
        //public int CategoryHierarchy { get; set; }
        //public int RecVersion2 { get; set; }
        //public int Partition2 { get; set; }
        //public int RecID2 { get; set; }
        //public int LogisticsPostalAddressLocation { get; set; }
        //public int RecVersion4 { get; set; }
        //public int Partition4 { get; set; }
        //public int RecID4 { get; set; }
        //public int RetailChannelTableOMOperatingUnitID { get; set; }
        //public int RecVersion6 { get; set; }
        //public int Partition6 { get; set; }
        //public int RecID6 { get; set; }
        //public int RecVersion8 { get; set; }
        //public int Partition8 { get; set; }
        //public int RecID8 { get; set; }
        //public int RecVersion10 { get; set; }
        //public int Partition10 { get; set; }
        //public int RecID10 { get; set; }
        //public string InventDimID { get; set; }
        //public int RecVersion11 { get; set; }
        //public int Partition11 { get; set; }
        //public int RecID11 { get; set; }
        //public int RecVersion3 { get; set; }
        //public int Partition3 { get; set; }
        //public int RecID3 { get; set; }
        //public int RecVersion5 { get; set; }
        //public int Partition5 { get; set; }
        //public int RecID5 { get; set; }
        //public int RecVersion7 { get; set; }
        //public int Partition7 { get; set; }
        //public int RecID7 { get; set; }
        //public int RecVersion9 { get; set; }
        //public int Partition9 { get; set; }
        //public int RecID9 { get; set; }
    }
}
